tap "hashicorp/tap"
brew "awscli"
brew "bat"
brew "colima"
brew "direnv"
brew "docker"
brew "exiftool"
brew "eza"
brew "ffmpeg"
brew "fd"
brew "fnm"
brew "fzf"
brew "gawk"
brew "gifsicle"
brew "git-delta"
brew "gnu-sed"
brew "go"
brew "gopls"
brew "goreleaser"
brew "grep"
brew "gum"
brew "helmfile"
brew "hugo"
brew "jq"
brew "kustomize"
brew "litecli"
brew "lua-language-server"
brew "luarocks"
brew "mas"
brew "mysql"
brew "neovim"
brew "protobuf"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "saml2aws"
brew "starship"
brew "stylua"
brew "tmux"
brew "tree-sitter"
brew "ttyd"
brew "typescript-language-server"
brew "uv"
brew "vhs"
brew "wget"
brew "yarn"
brew "zoxide"
brew "zsh"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"
cask "adobe-creative-cloud"
cask "appcleaner"
cask "claude-code"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "ghostty"
cask "google-japanese-ime"
cask "hiddenbar"
cask "inkdrop"
cask "numi"
cask "obs"
cask "obsidian"
cask "path-finder"
cask "popclip"
cask "qlmarkdown"
cask "rectangle"
cask "spotify"
cask "tableplus"
cask "the-unarchiver"
cask "typora"
cask "wezterm"
# mas apps require an App Store sign-in first; bootstrap tolerates their
# failure — sign in and re-run `brew bundle` to pick them up.
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
