tap "hashicorp/tap"
brew "awscli"
brew "bat"
brew "direnv"
brew "exiftool"
brew "eza"
brew "libidn2"
brew "unbound"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gawk"
brew "gifsicle"
brew "git-delta"
brew "gnu-sed"
brew "go"
brew "goreleaser"
brew "grep"
brew "gum"
brew "helmfile"
brew "hugo"
brew "jq"
brew "kustomize"
brew "libwebsockets"
brew "litecli"
brew "lua-language-server"
brew "luarocks"
brew "luv"
brew "mas"
brew "mysql"
brew "neovim"
brew "protobuf"
brew "ripgrep"
brew "saml2aws"
brew "starship"
brew "stylua"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "ttyd"
brew "vhs"
brew "wget"
brew "yarn"
brew "zoxide"
brew "zsh"
brew "hashicorp/tap/terraform-ls"
cask "adobe-creative-cloud"
cask "appcleaner"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "google-japanese-ime"
cask "hiddenbar"
cask "inkdrop"
cask "numi"
cask "obs"
cask "obsidian"
cask "path-finder"
cask "popclip"
cask "qlmarkdown"
cask "rectangle"
cask "spotify"
cask "tableplus"
cask "the-unarchiver"
cask "typora"
cask "wezterm"
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
